# Generated by Django 6.1.1 on 2026-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
